-   id: standard
    name: standard
    entry: standard --fix
    language: node
    types_or: [javascript, jsx]
    args: []
    require_serial: false
    additional_dependencies: ["standard@16.0.3"]
