-   id: standard
    name: standard
    entry: standard --fix
    language: node
    files: \.(json|js|jsx)$
    args: []
    require_serial: false
    additional_dependencies: ["standard@16.0.3", "@babel/eslint-parser@7.14.7"]
